### ISSUE TITLE
Infinite spinner on Hybris Select Payment Method

### ISSUE THREAD

**Issue by mcovarrubias** [Adyen/adyen-hybris#109]
**Hybris version**: 6.5.0
**Plugin version**: 4.1.0
**Description**
I'm trying to test the plugin, so i followed up the configuration steps according to this page:
https://docs.adyen.com/developers/plugins/hybris/set-up-the-add-on

but each time I click on the Credit Card radio button, a spinner appears and nothing else.
No JS errors on Web browser development console everything seems to be fine

![adyen](https://user-images.githubusercontent.com/20228751/54362900-6e554500-462f-11e9-8ea9-2a39b4a8d0ef.png)

Please advise!
Thanks

**Comment by rkewlani** [comment]
Hi @mcovarrubias ,
It seems that your originkey is not correct. Can you please check your originkey configuration in hybris backoffice ?

Regards,
Rajni

**Comment by mcovarrubias** [comment]
Hi @rkewlani, thank you for your support!
I have done what you ask for, but I'm not really sure if I'm doing it well.

![origin](https://user-images.githubusercontent.com/20228751/54451849-5e199480-4719-11e9-8d07-95362756d8d4.png)

I can see a JS file which has my originkey and other styff:

![adyen](https://user-images.githubusercontent.com/20228751/54451933-8acdac00-4719-11e9-8163-3902ad7eca60.png)

Thank you!

**Comment by rkewlani** [comment]
Hi mcovarrubias,
I am deleting your previous comment because you have shared your confidential environment information in that. Please follow detailed document to configure backoffice settings for hybris because your origin key is not correctly configured.
https://docs.adyen.com/developers/plugins/hybris/set-up-the-add-on#accountsettings
Regards,
Rajni

Adyen
