### ISSUE TITLE
Customer first name and last name not set in order when checkout as guest

### ISSUE THREAD

**Issue by maciek-marcinkowski** [Adyen/adyen-hybris#49]
Hello Adyen Team.

During payment process for not logged user user first name and last name is not saved in order (username is `Guest`) however it is provided during checkout process.
This becomes an issue if we want to use it further (send to external system etc.) and is inconsistent with Hybris process.

Regards
Maciek

**Comment by lancergr** [comment]
Hi @maciek-marcinkowski 
Thanks for your feedback and the Pull Request!

This Hybris extension relies on the underlying cart generation mechanism and by design introduces as less business logic as possible.
During the cart initialisation of de.hybris.platform.order.impl.DefaultCartFactory, the user is retrieved from userService.getCurrentUser and this defines the default Hybris behaviour that users would expect. So, on vanilla Hybris the username Guest is used by default.

I see your point on having the user details available for external systems, but I believe this shouldn't be in the scope of the Adyen extension but rather implement the proposed code as:
- an extra piece of logic within your checkout controllers
- or custom cart service or checkout facade

Let me know if this is OK with you.

Kind Regards,
Giorgos
Adyen

**Comment by maciek-marcinkowski** [comment]
Hi @lancergr 

I agree that at the very beginning of order placement user 'Guest' is set. However, at the last step of order placement the user is updated with 'First name' and 'Last name' taken from address form. This is an screen from vanilla hybris [link](https://s8.postimg.org/z7xbfr151/vanilla_Hybris-orders-1.png) and from hybris with Adyen installed [link](https://s8.postimg.org/br5ggzfk5/adyen_Hybris-orders-1.png).

The next issue is when we try to create an account after Guest order placement. On vanilla hybris the created account has 'Name' taken from address form and in case of Adyen register it looks like follows [(link)](https://s8.postimg.org/addtlogat/adyen-user-1.png) vs vanilla Hybris [(link)](https://s15.postimg.org/mohe6znwr/vanilla_Hybris_-_customers-2.png).

Best Regards
Maciek

**Comment by lancergr** [comment]
Hi @maciek-marcinkowski 

Could you check my last reply on your Pull Request?
https://github.com/Adyen/adyen-hybris/pull/50#discussion_r120639222

Best Regards,
Giorgos
Adyen
